### ISSUE TITLE
Trouble playing back match files with multiple maps

### ISSUE THREAD

**Issue by axc** [battlecode/battlecode-client#62]
To reproduce: just replay any match file with multiple maps. It usually doesn't get to the end.

     [java] Exception in thread "Thread-1" java.lang.RuntimeException: Unhandled object read: battlecode.serial.MatchHeader@1f743392
     [java] 	at battlecode.client.viewer.BufferedMatch.readMatch(BufferedMatch.java:116)
     [java] 	at java.lang.Thread.run(Thread.java:745)

**Comment by kazimuth** [comment]
Can't reproduce - it works fine on my machine. Do you have an example of a failing match file?

**Comment by kazimuth** [comment]
New files won't be a problem due to [battlecode-server #177](https://github.com/battlecode/battlecode-server/pull/177). All broken old files will still be malformed. Should we close?
